name: Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: npm ci

      - name: Установка браузеров Playwright
        run: npx playwright install --with-deps

      - name: Запуск тестов с HTML-отчётом
        run: npx playwright test --reporter=html

      - name: Загрузка HTML-отчёта
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Деплой в GitHub Pages
        uses: actions/deploy-pages@v2